version: '3.2'

services:

  redis:
    image: redis:2.8.19
#    ports:
#      - "6999:6379"

  selenium:
    image: selenium/standalone-firefox-debug
    ports:
      - "4444:4444"

  web:
    build:
      context: .
      dockerfile: docker/django_crawler.dockerfile
#    hostname: web
    command: ./run_web.sh
    ports:
      - "8000:8000"
    links:
      - redis
      - selenium
    environment:
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444

#  worker:
#    build:
#      context: .
#      dockerfile: docker/celery.dockerfile
#    command: ./run_celery.sh
#    links:
#      - redis
